### ISSUE TITLE
Only generates x86 specific cmake

### ISSUE THREAD

**Issue by triscuitcircuit** [Enhex/premake-cmake#10]
I tried using this to build a CmakeList.txt from [SOIL2](https://github.com/SpartanJ/SOIL2)'s premake5, and it only seems to generate x86 specific CmakeLists.txt.

Is there a way to disable this? 

Thanks

**Comment by Enhex** [comment]
I don't know how CMake can be x86 specific.
I'm guessing it's something that project generates.
Perhaps post the x86 specific stuff?

**Comment by triscuitcircuit** [comment]
part of generated "soil2-static-lib.cmake" file ( it doesnt include anything else besides x86)
```
if(CMAKE_BUILD_TYPE STREQUAL x86_64-debug)
  set_target_properties("soil2-static-lib" PROPERTIES
    OUTPUT_NAME "soil2-debug"
    ARCHIVE_OUTPUT_DIRECTORY "/Volumes/MacStorage/github/SOIL2/lib/macosx"
    LIBRARY_OUTPUT_DIRECTORY "/Volumes/MacStorage/github/SOIL2/lib/macosx"
    RUNTIME_OUTPUT_DIRECTORY "/Volumes/MacStorage/github/SOIL2/lib/macosx"
  )
endif()
target_include_directories("soil2-static-lib" PRIVATE
  $<$<CONFIG:x86_64-debug>:/Volumes/MacStorage/github/src/cmake>
)
target_compile_definitions("soil2-static-lib" PRIVATE
  $<$<CONFIG:x86_64-debug>:DEBUG>
  $<$<CONFIG:x86_64-debug>:GL_SILENCE_DEPRECATION>
)
target_link_directories("soil2-static-lib" PRIVATE
)
target_link_libraries("soil2-static-lib"
)
target_compile_options("soil2-static-lib" PRIVATE
  $<$<CONFIG:x86_64-debug>:-Wall>
  $<$<AND:$<CONFIG:x86_64-debug>,$<COMPILE_LANGUAGE:C>>:-m64>
  $<$<AND:$<CONFIG:x86_64-debug>,$<COMPILE_LANGUAGE:C>>:-g>
  $<$<AND:$<CONFIG:x86_64-debug>,$<COMPILE_LANGUAGE:CXX>>:-m64>
  $<$<AND:$<CONFIG:x86_64-debug>,$<COMPILE_LANGUAGE:CXX>>:-g>
)
```

I already have a CmakeLists.txt that I made for SOIL2, but i figured that this was an issue with "premake-cmake" and still worth reporting right?

**Comment by triscuitcircuit** [comment]
Nevermind I wasnt thinking. Issue solved. THanks for your help!

**Comment by benphelps** [comment]
@triscuitcircuit What was the issue?  I'm running into this and can't seem to figure it out.

**Comment by triscuitcircuit** [comment]
I think there was actually an issue with it generating only for x86, and I ended up using a custom cmake for soil.
